# Generated by Django 2.2.10 on 2020-07-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=1000, verbose_name='название опроса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('start_pub', models.DateField()),
                ('end_pub', models.DateField()),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
                'ordering': ['start_pub', 'end_pub'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=1000, verbose_name='текст вопроса')),
                ('kind', models.CharField(choices=[('a', 'ответ текстом'), ('b', 'ответ с выбором одного варианта'), ('c', 'ответ с выбором нескольких вариантов')], max_length=1)),
                ('poll', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='app.Poll', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
